---
name: Survival
version: 1.1.0
main: Survival\Main
description: Dont lose your itens in survival
api: 2.0.0
author: NATANBX0

commands:
  setsurvival:
    description: define o mundo survival
    permission: survival.set

  rmsurvival:
    description: remove o survival de um mundo
    permission: survival.remove

  listsurvival:
    description: lista todos mundos aplicados com o survival
    default: op

permissions:
  survival.set:
    description: define o mundo survival
    default: op

  survival.remove:
    description: remove o survival de um mundo
    default: op

  survival.list:
    description: lista todos mundos aplicados com o survival
    default: op
